'use server';
import { prisma } from '@/lib/db'; import { currentUser,can } from '@/lib/access'; import { calcDeal } from '@/lib/money'; import { audit } from '@/lib/audit'; import { redirect } from 'next/navigation'; import { revalidatePath } from 'next/cache';
export async function createDeal(fd:FormData){const u=await currentUser();if(!can(u,'deals.create')) throw new Error('Нет прав');const clientId=String(fd.get('clientId'));const client=await prisma.client.findFirst({where:{id:clientId,assignedTo:u.id}});if(!client) throw new Error('Сделку может создать только ответственный за клиента');const amount=Number(fd.get('amount')),partnerRate=Number(fd.get('partnerRate')),clientRate=Number(fd.get('clientRate'));const employeeCount=await prisma.user.count({where:{isActive:true,participatesInEmployeeBank:true}});const c=calcDeal(amount,partnerRate,clientRate,employeeCount);const d=await prisma.deal.create({data:{title:String(fd.get('title')),clientId,partnerId:String(fd.get('partnerId')||'')||null,assignedTo:u.id,createdBy:u.id,amount,partnerRate,clientRate,...c,employeeCount,status:'NEW'}});await prisma.userPreference.upsert({where:{userId:u.id},update:{lastPartnerRate:partnerRate,lastClientRate:clientRate},create:{userId:u.id,lastPartnerRate:partnerRate,lastClientRate:clientRate}});await audit(u.id,'CREATE','deal',d.id,{amount,partnerRate,clientRate});redirect(`/deals/${d.id}`)}
export async function addPayment(fd:FormData){const u=await currentUser();const id=String(fd.get('dealId'));const d=await prisma.deal.findUniqueOrThrow({where:{id}});if(!(d.assignedTo===u.id||can(u,'deals.edit_any'))) throw new Error('Нет прав');await prisma.dealPayment.create({data:{dealId:id,direction:String(fd.get('direction')) as any,amount:Number(fd.get('amount')),note:String(fd.get('note')||'')||null,createdBy:u.id}});await audit(u.id,'ADD_PAYMENT','deal',id);revalidatePath(`/deals/${id}`)}
export async function completeDeal(fd:FormData){const u=await currentUser();const id=String(fd.get('dealId'));const d=await prisma.deal.findUniqueOrThrow({where:{id}});if(!(d.assignedTo===u.id||can(u,'deals.complete'))) throw new Error('Нет прав');if(d.status==='COMPLETED') return;const users=await prisma.user.findMany({where:{isActive:true,participatesInEmployeeBank:true},select:{id:true}});const perEmployee=Math.round((Number(d.employeesShare)/Math.max(users.length,1))*100)/100;await prisma.$transaction(async(tx)=>{await tx.deal.update({where:{id},data:{status:'COMPLETED',closedAt:new Date(),employeeCount:users.length,perEmployeeShare:perEmployee}});await tx.bankLedgerEntry.createMany({data:[{bank:'COMPANY',kind:'DEAL_ACCRUAL',amount:d.companyShare,dealId:id},{bank:'EMPLOYEES',kind:'DEAL_ACCRUAL',amount:d.employeesShare,dealId:id}]});for(const person of users){await tx.employeeLedgerEntry.create({data:{userId:person.id,kind:'DEAL_ACCRUAL',amount:perEmployee,dealId:id,note:`Доля со сделки ${d.title}`}})}});await audit(u.id,'COMPLETE','deal',id);revalidatePath(`/deals/${id}`);revalidatePath('/')}
export async function addComment(fd:FormData){const u=await currentUser();const dealId=String(fd.get('dealId'));await prisma.comment.create({data:{entityType:'DEAL',dealId,authorId:u.id,text:String(fd.get('text'))}});await audit(u.id,'COMMENT','deal',dealId);revalidatePath(`/deals/${dealId}`)}

export async function editComment(fd:FormData){const u=await currentUser();const commentId=String(fd.get('commentId'));const c=await prisma.comment.findUniqueOrThrow({where:{id:commentId}});if(c.authorId!==u.id&&u.role!=='SUPER_ADMIN') throw new Error('Нет прав');const text=String(fd.get('text'));await prisma.$transaction([prisma.commentRevision.create({data:{commentId:c.id,text:c.text,editedBy:u.id}}),prisma.comment.update({where:{id:c.id},data:{text}})]);await audit(u.id,'EDIT_COMMENT','comment',c.id);if(c.dealId) revalidatePath(`/deals/${c.dealId}`)}
export async function deleteComment(fd:FormData){const u=await currentUser();const commentId=String(fd.get('commentId'));const c=await prisma.comment.findUniqueOrThrow({where:{id:commentId}});if(c.authorId!==u.id&&u.role!=='SUPER_ADMIN') throw new Error('Нет прав');await prisma.$transaction([prisma.commentRevision.create({data:{commentId:c.id,text:c.text,editedBy:u.id}}),prisma.comment.update({where:{id:c.id},data:{deletedAt:new Date()}})]);await audit(u.id,'DELETE_COMMENT','comment',c.id);if(c.dealId) revalidatePath(`/deals/${c.dealId}`)}
