import {randomUUID} from 'node:crypto';
import {prisma} from '@/lib/db';
import {currentUser} from '@/lib/access';
import {fmt,calcExpense} from '@/lib/money';
import {businessToday,displayDate,BUSINESS_TIME_ZONE} from '@/lib/dates';
import ExpenseForm,{ExpenseDelete} from './ExpenseForm';
export default async function Expenses(){
 const u=await currentUser(),today=businessToday();
 const [rows,total]=await Promise.all([prisma.expense.findMany({include:{author:{select:{displayName:true}}},orderBy:[{spentOn:'desc'},{createdAt:'desc'}]}),prisma.expense.aggregate({where:{deletedAt:null},_sum:{amount:true}})]);
 return <div className="stack"><div className="top"><div><h1 className="title">Траты</h1><div className="sub">Расходы команды в USDT. Общие банки и личные балансы обновляются автоматически.</div></div></div><div className="grid cards"><div className="card"><div className="muted">Всего потрачено</div><div className="kpi">{fmt(Number(total._sum.amount??0))}</div></div><div className="card"><div className="muted">За счёт компании</div><div className="kpi">{fmt(rows.filter(e=>!e.deletedAt).reduce((s,e)=>s+calcExpense(Number(e.amount)).companyShare,0))}</div></div><div className="card"><div className="muted">За счёт сотрудников</div><div className="kpi">{fmt(rows.filter(e=>!e.deletedAt).reduce((s,e)=>s+calcExpense(Number(e.amount)).employeesShare,0))}</div></div></div><div className="card stack"><h2 className="section">Добавить расход</h2><ExpenseForm today={today} requestId={randomUUID()}/></div><h2 className="section">История трат</h2>{!rows.length&&<div className="card muted">Расходов пока нет.</div>}{rows.map(e=>{const editable=e.authorId===u.id||u.role==='SUPER_ADMIN',version=e.updatedAt.toISOString();return <article className="card stack" key={e.id}><div className="split"><div><b className="expense-description">{e.description}</b><div className="sub">{displayDate(e.spentOn)} · {e.author.displayName}</div></div><b className={e.deletedAt?'muted':'bad'}>{fmt(String(e.amount))}</b></div><div className="sub">Внесено {e.createdAt.toLocaleString('ru-RU',{timeZone:BUSINESS_TIME_ZONE})}; добавление и изменения учитываются в период сохранения.</div>{e.deletedAt?<div className="badge">Удалён — списание отменено</div>:editable&&<details><summary>Изменить расход</summary><div className="stack details-content"><ExpenseForm today={today} item={{id:e.id,spentOn:e.spentOn.toISOString().slice(0,10),description:e.description,amount:String(e.amount),version}}/><ExpenseDelete id={e.id} version={version}/></div></details>}</article>;})}</div>;
}
