import test from 'node:test';import assert from 'node:assert/strict';
import {calcDeal,splitEmployeeShare,round2} from '../src/lib/money';
import {reconcileDeal,ensureAllocations} from '../src/lib/deal-ledger';
function fixture(users:string[],initial=125){
 const deal:any={id:'deal',companyShare:375,employeesShare:125,posted:true,allocations:[],employeeCount:1};
 const banks:any[]=[{dealId:'deal',bank:'COMPANY',amount:375},{dealId:'deal',bank:'EMPLOYEES',amount:125}];
 const ledger:any[]=[{dealId:'deal',userId:'admin',kind:'DEAL_ACCRUAL',amount:initial}];
 const net=(rows:any[],query:any)=>round2(rows.filter(r=>Object.entries(query).every(([k,v])=>r[k]===v)).reduce((s,r)=>s+Number(r.amount),0));
 const tx:any={deal:{findUniqueOrThrow:async()=>deal,update:async({data}:any)=>Object.assign(deal,data)},dealAllocation:{createMany:async({data}:any)=>deal.allocations.push(...data)},user:{findMany:async()=>users.map(id=>({id}))},employeeLedgerEntry:{findMany:async()=>[{userId:'admin'}],groupBy:async()=>[...new Set(ledger.map(x=>x.userId))].map(userId=>({userId,_sum:{amount:net(ledger,{dealId:'deal',userId})}})),create:async({data}:any)=>ledger.push(data)},bankLedgerEntry:{aggregate:async({where}:any)=>({_sum:{amount:net(banks,where)}}),create:async({data}:any)=>banks.push(data)},auditLog:{create:async()=>({})}};
 return{deal,banks,ledger,tx,net};
}
test('500 profit gives 375 company, 125 employees, 31.25 per person',()=>assert.deepEqual(calcDeal(10000,90,85),{partnerAmount:9000,clientAmount:8500,fee:500,companyShare:375,employeesShare:125,perEmployeeShare:31.25}));
test('cent allocations preserve the exact total including losses',()=>{for(const total of [125,.01,.02,.03,.05,-.01,-.05,-125]){const values=splitEmployeeShare(total);assert.equal(values.length,4);assert.equal(Math.round(values.reduce((a,b)=>a+b,0)*100),Math.round(total*100));}});
test('legacy one-person accrual is corrected without changing company or team bank',async()=>{const f=fixture(['admin']);await ensureAllocations(f.tx,'deal');await reconcileDeal(f.tx,'deal',true,'admin','repair');assert.equal(f.net(f.ledger,{userId:'admin'}),31.25);assert.equal(f.net(f.banks,{bank:'EMPLOYEES'}),125);assert.equal(f.deal.allocations.filter((a:any)=>!a.userId).length,3);const before=f.ledger.length;await reconcileDeal(f.tx,'deal',true,'admin','repair again');assert.equal(f.ledger.length,before);});
test('four members share equally and reopening/deleting/re-restoring is idempotent',async()=>{const f=fixture(['admin','two','three','four']);await ensureAllocations(f.tx,'deal');await reconcileDeal(f.tx,'deal',true,'admin','repair');for(const userId of ['admin','two','three','four'])assert.equal(f.net(f.ledger,{userId}),31.25);await reconcileDeal(f.tx,'deal',false,'admin','delete');await reconcileDeal(f.tx,'deal',false,'admin','delete again');assert.equal(f.net(f.banks,{bank:'COMPANY'}),0);assert.equal(f.net(f.banks,{bank:'EMPLOYEES'}),0);for(const userId of ['admin','two','three','four'])assert.equal(f.net(f.ledger,{userId}),0);await reconcileDeal(f.tx,'deal',true,'admin','restore');await reconcileDeal(f.tx,'deal',true,'admin','restore again');for(const userId of ['admin','two','three','four'])assert.equal(f.net(f.ledger,{userId}),31.25);});
test('actual payouts are preserved when earnings are reversed',async()=>{const f=fixture(['admin']);await ensureAllocations(f.tx,'deal');await reconcileDeal(f.tx,'deal',true,'admin','repair');f.ledger.push({userId:'admin',kind:'PAYOUT',amount:-10});f.banks.push({bank:'EMPLOYEES',kind:'PAYOUT',amount:-10});await reconcileDeal(f.tx,'deal',false,'admin','delete');assert.equal(f.net(f.ledger,{userId:'admin'}),-10);assert.equal(f.net(f.banks,{bank:'EMPLOYEES'}),-10);});
