import test from 'node:test';import assert from 'node:assert/strict';
import {periodFor,priorPeriod,dateWhere,inPeriod,baseDealWhere,paymentMatches,queryLink} from '../src/lib/filters';
import {reportMetrics,percentageChange,type ReportDeal,type ReportExpense} from '../src/lib/analytics';
import {hasPermission} from '../src/lib/permissions';
import {csvCell} from '../src/components/ReportExport';
const now=new Date('2026-10-03T08:00:00Z');
function deal(overrides:Partial<ReportDeal>={}):ReportDeal {return {id:'d',title:'D',clientId:'c',partnerId:'p',assignedTo:'u',amount:10000,partnerAmount:9000,clientAmount:8500,fee:500,companyShare:375,employeesShare:125,dealDate:new Date('2026-09-30T00:00:00Z'),closedAt:new Date('2026-10-02T08:00:00Z'),status:'COMPLETED',client:{name:'Client'},partner:{name:'Partner'},assignee:{displayName:'User'},payments:[{direction:'PARTNER_TO_US',amount:9000},{direction:'US_TO_CLIENT',amount:8500}],...overrides};}
function expense(overrides:Partial<ReportExpense>={}):ReportExpense{return {id:'e',dealId:'d',description:'Fee',category:'COMMISSION',amount:100,spentOn:new Date('2026-10-02T00:00:00Z'),authorId:'u',...overrides};}
test('period filters use the user timezone and include the entire last day',()=>{assert.deepEqual(periodFor({period:'month'},'all',now),{from:'2026-10-01',to:'2026-10-03'});assert.deepEqual(periodFor({period:'previous_month'},'all',now),{from:'2026-09-01',to:'2026-09-30'});assert.deepEqual(periodFor({period:'today'},'all',new Date('2026-10-02T21:00:00Z')),{from:'2026-10-03',to:'2026-10-03'});const p={from:'2026-10-02',to:'2026-10-02'};assert.equal(inPeriod(new Date('2026-10-02T18:59:59Z'),p),true);assert.equal(inPeriod(new Date('2026-10-02T19:00:00Z'),p),false);});
test('custom periods reject invalid dates and reversed ranges',()=>{assert.throws(()=>periodFor({period:'custom',from:'2026-02-29',to:'2026-03-01'}));assert.throws(()=>periodFor({period:'custom',from:'2026-10-03',to:'2026-10-01'}));assert.deepEqual(priorPeriod({from:'2026-10-01',to:'2026-10-03'}),{from:'2026-09-28',to:'2026-09-30'});assert.equal(dateWhere(null),undefined);});
test('source and tag combine, amount ranges are validated, and prototype keys cannot become statuses',()=>{const where=baseDealWhere({source:'Referral',tag:'VIP',min:'1,50',max:'100',status:'toString'});assert.deepEqual(where.client,{source:{contains:'Referral',mode:'insensitive'},tags:{has:'VIP'}});assert.deepEqual(where.amount,{gte:1.5,lte:100});assert.equal(where.status,undefined);assert.throws(()=>baseDealWhere({min:'100',max:'1'}));assert.throws(()=>baseDealWhere({min:'NaN'}));});
test('payment filters use actual recorded amounts and tolerate cent rounding',()=>{assert.equal(paymentMatches(deal(),'settled'),true);assert.equal(paymentMatches(deal({payments:[]}),'partner_due'),true);assert.equal(paymentMatches(deal({payments:[{direction:'PARTNER_TO_US',amount:9100}]}),'partner_due'),false);assert.equal(paymentMatches(deal({payments:[]}),'client_due'),true);});
test('business date controls turnover, completion date controls recognition, expenses have their own date',()=>{const result=reportMetrics([deal()],[expense()],{from:'2026-10-01',to:'2026-10-03'});assert.equal(result.count,0);assert.equal(result.turnover,0);assert.equal(result.completed,1);assert.equal(result.gross,500);assert.equal(result.cost,100);assert.equal(result.net,400);assert.equal(result.company,300);assert.equal(result.team,100);const september=reportMetrics([deal()],[expense()],{from:'2026-09-01',to:'2026-09-30'});assert.equal(september.turnover,10000);assert.equal(september.gross,0);assert.equal(september.cost,0);});
test('unfinished deals contribute expected volume but never recognised income',()=>{const result=reportMetrics([deal({status:'IN_PROGRESS',dealDate:new Date('2026-10-02'),closedAt:null})],[],{from:'2026-10-01',to:'2026-10-03'});assert.equal(result.turnover,10000);assert.equal(result.gross,0);assert.equal(result.completed,0);});
test('report shares preserve exact cents and negative results',()=>{const result=reportMetrics([deal()],[expense({amount:1000.01})],null);assert.equal(result.net,-500.01);assert.equal(Math.round((result.company+result.team)*100),-50001);assert.equal(percentageChange(20,0),null);assert.equal(percentageChange(30,20),50);assert.equal(percentageChange(-20,-10),-100);});
test('read-only denies working changes even with maliciously or accidentally enabled permissions',()=>{const u={role:'USER',isReadOnly:true,permissions:[{key:'deals.create',enabled:true},{key:'expenses.create',enabled:true},{key:'analytics.view',enabled:true},{key:'payouts.view_all',enabled:true}]};assert.equal(hasPermission(u,'deals.create'),false);assert.equal(hasPermission(u,'expenses.create'),false);assert.equal(hasPermission(u,'analytics.view'),true);assert.equal(hasPermission(u,'payouts.view_all'),true);assert.equal(hasPermission(u,'banks.view'),false);assert.equal(hasPermission({...u,role:'SUPER_ADMIN'},'deals.create'),true);});
test('ordinary users do not gain bank or expense access from participating in profits',()=>{const u={role:'USER',isReadOnly:false,permissions:[]};assert.equal(hasPermission(u,'banks.view'),false);assert.equal(hasPermission(u,'expenses.create'),false);assert.equal(hasPermission({...u,permissions:[{key:'expenses.create',enabled:true}]},'expenses.create'),true);});
test('CSV protects formula text and retains quoted names',()=>{assert.equal(csvCell('=HYPERLINK("x")'),'"\'=HYPERLINK(""x"")"');assert.equal(csvCell('Alice "A"'),'"Alice ""A"""');assert.equal(csvCell('one;two'),'"one;two"');});
test('drill-down links retain periods and safely encode contact names',()=>{const link=queryLink('/deals',{period:'custom',from:'2026-10-01',to:'2026-10-03',q:'a & b'},{status:'COMPLETED',dateBasis:'closed'});assert.match(link,/q=a\+%26\+b/);assert.match(link,/dateBasis=closed/);assert.match(link,/from=2026-10-01/);});
import {payoutWindow} from '../src/lib/payouts';
test('payout windows switch at Yekaterinburg midnight and include the 15th once',()=>{const first=payoutWindow(new Date('2026-10-15T18:59:59Z'));assert.equal(first.start.toISOString(),'2026-09-30T19:00:00.000Z');assert.equal(first.end.toISOString(),'2026-10-15T18:59:59.999Z');assert.equal(first.due.toISOString(),'2026-10-15T07:00:00.000Z');const second=payoutWindow(new Date('2026-10-15T19:00:00Z'));assert.equal(second.start.toISOString(),'2026-10-15T19:00:00.000Z');assert.equal(second.end.toISOString(),'2026-10-31T18:59:59.999Z');assert.equal(second.due.toISOString(),'2026-10-31T07:00:00.000Z');});
