'use client';
import { useActionState,useMemo,useState } from 'react';
import { calcDeal,fmt } from '@/lib/money';
import CounterpartyPicker from '@/components/CounterpartyPicker';
import { createDeal } from '../actions';
export default function DealForm({clients,partners,defaults,canCreateClient,canCreatePartner}:{clients:any[];partners:any[];defaults:{partner:number;client:number};canCreateClient:boolean;canCreatePartner:boolean}){
 const[state,action,pending]=useActionState(createDeal,{error:''}),[title,setTitle]=useState(''),[amount,setAmount]=useState(''),[pr,setPr]=useState(String(defaults.partner)),[cr,setCr]=useState(String(defaults.client));
 const n=(s:string)=>Number(s.replace(',','.'))||0;
 const c=useMemo(()=>calcDeal(n(amount),n(pr),n(cr)),[amount,pr,cr]);
 return <form action={action} className="card stack"><div className="field"><label htmlFor="deal-title">Название сделки</label><input id="deal-title" name="title" value={title} onChange={e=>setTitle(e.target.value)} required maxLength={200} placeholder="Например: Alex / October #1"/></div><div className="formgrid"><CounterpartyPicker label="Клиент" prefix="client" options={clients} required canCreate={canCreateClient}/><CounterpartyPicker label="Партнёр" prefix="partner" options={partners} canCreate={canCreatePartner}/><div className="field"><label>Сумма, USDT</label><input name="amount" inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)} required/></div><div className="field"><label>Партнёр, %</label><input name="partnerRate" inputMode="decimal" value={pr} onChange={e=>setPr(e.target.value)} required/></div><div className="field"><label>Клиент, %</label><input name="clientRate" inputMode="decimal" value={cr} onChange={e=>setCr(e.target.value)} required/></div></div><div className="calc"><div className="row"><span>Партнёр вернёт</span><b>{fmt(c.partnerAmount)}</b></div><div className="row"><span>Клиент получит</span><b>{fmt(c.clientAmount)}</b></div><hr/><div className="row"><span>Прибыль сделки</span><b className={c.fee<0?'bad':'good'}>{fmt(c.fee)}</b></div><div className="row"><span>Компания — 75%</span><span>{fmt(c.companyShare)}</span></div><div className="row"><span>Все сотрудники — 25%</span><span>{fmt(c.employeesShare)}</span></div><div className="row"><b>Личная доля каждого из четырёх</b><b>{fmt(c.perEmployeeShare)}</b></div><div className="sub">Начисляется после завершения сделки. Расчёт всегда на четверых; округление долей может отличаться на 0,01 USDT.</div></div>{state.error&&<div role="alert" className="notice">{state.error}</div>}<div><button className="btn primary" disabled={pending}>{pending?'Создание…':'Создать сделку'}</button></div></form>;
}
