import { prisma } from '@/lib/db'; import { currentUser,can } from '@/lib/access'; import { fmt } from '@/lib/money'; import { payoutWindow,payoutAmounts } from '@/lib/payouts'; import { confirmPayout } from './actions';

async function ensurePeriod(userId:string){
  const w=payoutWindow();
  const accrual=await prisma.employeeLedgerEntry.aggregate({_sum:{amount:true},where:{userId,kind:{in:['DEAL_ACCRUAL','ADJUSTMENT','EXPENSE']},createdAt:{gte:w.start,lte:w.end}}});
  const priorBalance=await prisma.employeeLedgerEntry.aggregate({_sum:{amount:true},where:{userId,createdAt:{lt:w.start}}});
  const current=await prisma.employeePayoutPeriod.findUnique({where:{userId_periodStart_periodEnd:{userId,periodStart:w.start,periodEnd:w.end}}});
  if(current){ if(current.status==='OPEN') return prisma.employeePayoutPeriod.update({where:{id:current.id},data:{...payoutAmounts(Number(accrual._sum.amount||0),Number(priorBalance._sum.amount||0))}}); return current; }
  return prisma.employeePayoutPeriod.create({data:{userId,periodStart:w.start,periodEnd:w.end,dueDate:w.due,...payoutAmounts(Number(accrual._sum.amount||0),Number(priorBalance._sum.amount||0))}})
}

export default async function Payouts(){const u=await currentUser();const period=await ensurePeriod(u.id);const balance=await prisma.employeeLedgerEntry.aggregate({_sum:{amount:true},where:{userId:u.id}});const due=Number(period.amountDue)+Number(period.carriedForward);const all=can(u,'payouts.view_all')?await prisma.employeePayoutPeriod.findMany({include:{user:true},orderBy:{dueDate:'desc'},take:30}):[];return <div className="stack"><div className="top"><div><div className="title">Выплаты</div><div className="sub">15-го и в последний календарный день месяца</div></div></div><div className="grid cards"><div className="card"><div className="muted">Мой текущий баланс</div><div className="kpi good">{fmt(Number(balance._sum.amount||0))}</div></div><div className="card"><div className="muted">К выплате за период</div><div className="kpi">{fmt(due)}</div><div className="sub">{period.periodStart.toLocaleDateString('ru-RU')} – {period.periodEnd.toLocaleDateString('ru-RU')}</div></div><div className="card"><div className="muted">Дата выплаты</div><div className="kpi">{period.dueDate.toLocaleDateString('ru-RU')}</div></div></div>{period.status==='OPEN'&&new Date()>=period.dueDate?<div className="card stack"><div className="section">Подтверждение получения</div><p className="muted">Если получили всю сумму — оставьте поле как есть. Если получили меньше или 0, укажите фактическую сумму; остаток перенесётся.</p><form action={confirmPayout} className="formgrid"><input type="hidden" name="periodId" value={period.id}/><div className="field"><label>Фактически получил, USDT</label><input name="received" inputMode="decimal" defaultValue={due.toFixed(2)}/></div><div className="field" style={{alignSelf:'end'}}><button className="btn primary">Подтвердить</button></div></form></div>:period.status==='OPEN'?<div className="notice">Подтверждение откроется {period.dueDate.toLocaleDateString('ru-RU')}.</div>:<div className="success">Подтверждено: {fmt(Number(period.amountConfirmed))}. Перенос: {fmt(Number(period.carriedForward))}. Статус: {period.status}</div>}{all.length>0&&<div><div className="section">Сводка выплат команды</div><div className="table-scroll" role="region" aria-label="Таблица — прокрутите вправо"><table className="table"><thead><tr><th>Сотрудник</th><th>Период</th><th>Положено</th><th>Получено</th><th>Перенос</th><th>Статус</th></tr></thead><tbody>{all.map(p=><tr key={p.id}><td>{p.user.displayName}</td><td>{p.periodStart.toLocaleDateString('ru-RU')} – {p.periodEnd.toLocaleDateString('ru-RU')}</td><td>{fmt(Number(p.amountDue))}</td><td>{fmt(Number(p.amountConfirmed))}</td><td>{fmt(Number(p.carriedForward))}</td><td><span className="badge">{p.status}</span></td></tr>)}</tbody></table></div></div>}</div>}
