 'use client';
import Link from 'next/link';import {usePathname} from 'next/navigation';import {useEffect,useState} from 'react';
function Icon({kind}:{kind:string}){const paths:Record<string,string>={home:'M3 3h7v7H3z M14 3h7v7h-7z M3 14h7v7H3z M14 14h7v7h-7z',deals:'M4 6h16v15H4z M8 6V3h8v3 M4 12h16',clients:'M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2 M9 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8 M17 4a4 4 0 0 1 0 8 M22 21v-2a4 4 0 0 0-3-4',partners:'M12 3l9 5-9 5-9-5z M3 12l9 5 9-5 M3 16l9 5 9-5',expenses:'M4 3h16v18l-4-2-4 2-4-2-4 2z M8 8h8 M8 12h6',analytics:'M3 3v18h18 M7 15l4-5 4 3 5-8',payouts:'M3 6h18v14H3z M3 10h18 M16 15h2',profile:'M20 21v-2a7 7 0 0 0-14 0v2 M13 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8',regulations:'M4 3h12l4 4v14H4z M14 3v5h6 M8 12h8 M8 16h6',users:'M3 12h18 M12 3v18 M5 5l14 14 M19 5L5 19',audit:'M3 12a9 9 0 1 0 3-7 M3 3v5h5 M12 7v5l3 2',help:'M12 3a9 9 0 1 0 0 18 9 9 0 0 0 0-18 M9 9a3 3 0 1 1 4 3v2 M12 17h.01'};return <svg width="19" height="19" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={paths[kind]??paths.home}/></svg>;}
export default function Navigation({admin,analytics,name,readOnly,today,footer}:{admin:boolean;analytics:boolean;name:string;readOnly:boolean;today:string;footer:React.ReactNode}){
 const pathname=usePathname(),[open,setOpen]=useState(false);
 useEffect(()=>{if(!open)return;const close=(e:KeyboardEvent)=>{if(e.key==='Escape')setOpen(false);};document.addEventListener('keydown',close);return()=>document.removeEventListener('keydown',close);},[open]);
 const links=[['/','Обзор','home'],['/deals','Сделки','deals'],['/clients','Клиенты','clients'],['/partners','Партнёры','partners'],['/expenses','Траты','expenses'],...(analytics?[['/analytics','Аналитика','analytics']]:[]),['/payouts','Выплаты','payouts'],['/regulations','Регламенты','regulations'],['/profile','Мой профиль','profile'],['/help','Помощь','help'],...(admin?[['/admin/users','Команда и доступ','users'],['/admin/audit','История действий','audit']]:[])];
 return <><header className="mobile-bar"><Link href="/" className="brand" onClick={()=>setOpen(false)}>Laund<span>ra</span></Link><button className="menu-button" type="button" aria-label={open?'Закрыть меню':'Открыть меню'} aria-expanded={open} aria-controls="app-sidebar" onClick={()=>setOpen(!open)}>{open?'Закрыть':'☰ Меню'}</button></header>{open&&<button className="menu-backdrop" aria-label="Закрыть меню" onClick={()=>setOpen(false)}/>}<aside id="app-sidebar" className={`side ${open?'is-open':''}`}><Link href="/" className="brand desktop-brand">Laund<span>ra</span></Link><div className="side-caption">Рабочее пространство</div><nav className="nav" aria-label="Разделы приложения">{links.map(([href,label,icon])=><Link key={href} href={href} onClick={()=>setOpen(false)} aria-current={(href==='/'?pathname==='/':pathname.startsWith(href))?'page':undefined}><Icon kind={icon}/><span>{label}</span></Link>)}</nav><div className="side-footer"><div className="user-chip"><span className="avatar">{name.slice(0,1).toUpperCase()}</span><div><b>{name}</b><div className="sub">{admin?'Администратор':readOnly?'Только просмотр':'Участник команды'}</div></div></div>{footer}</div></aside><div className="workspace-bar"><span>Команда / {links.find(([href])=>href==='/'?pathname==='/':pathname.startsWith(href))?.[1]??'Рабочее пространство'}</span><span className="workspace-date">{today} <i className="online-dot"/> Laundra</span></div></>;
}
