 'use client';
import {useState,useActionState} from 'react';import {createUser,updatePermissions,type UserState} from '@/app/(app)/admin/users/actions';import {PERMISSIONS,PERMISSION_LABELS,PRESETS} from '@/lib/permissions';
type User={id:string;displayName:string;username:string;isActive:boolean;isReadOnly:boolean;participatesInEmployeeBank:boolean;keys:string[]};
export default function UserForm({user}:{user?:User}){
 const [state,action,pending]=useActionState(user?updatePermissions:createUser,{} as UserState);
 const [keys,setKeys]=useState<string[]>(user?.keys??[...PRESETS.EMPLOYEE]),[readOnly,setReadOnly]=useState(user?.isReadOnly??false),[participates,setParticipates]=useState(user?.participatesInEmployeeBank??false),[preset,setPreset]=useState(user?'CUSTOM':'EMPLOYEE');
 function selectPreset(value:string){setPreset(value);if(value==='CUSTOM')return;setKeys([...PRESETS[value as keyof typeof PRESETS]]);setReadOnly(value!=='EMPLOYEE');setParticipates(false);}
 return <form action={action} className="card stack">{user?<><input type="hidden" name="userId" value={user.id}/><div className="split"><div><h2 className="section">{user.displayName}</h2><div className="sub">@{user.username}</div></div><span className="badge">{user.isReadOnly?'Только просмотр':'Участник'}</span></div></>:<h2 className="section">Новый пользователь</h2>}<div className="formgrid">{!user&&<><div className="field"><label>Логин</label><input name="username" required minLength={3} maxLength={50} autoComplete="off"/></div><div className="field"><label>Имя</label><input name="displayName" required maxLength={100}/></div><div className="field"><label>Временный пароль — от 16 символов</label><input name="password" type="password" required minLength={16} autoComplete="new-password"/></div></>}<div className="field"><label>Набор прав</label><select value={preset} onChange={e=>selectPreset(e.target.value)}><option value="EMPLOYEE">Сотрудник</option><option value="OBSERVER">Наблюдатель — отчёты и банки</option><option value="GUEST">Гость — только просмотр</option><option value="CUSTOM">Настроить вручную</option></select></div></div><div className="split"><label className="check"><input name="isReadOnly" type="checkbox" checked={readOnly} onChange={e=>{setReadOnly(e.target.checked);setPreset('CUSTOM');if(e.target.checked)setParticipates(false);}}/> Только просмотр — запрет любых рабочих изменений</label>{user&&<label className="check"><input type="checkbox" name="isActive" defaultChecked={user.isActive}/> Активен</label>}</div><label className="check"><input name="participatesInEmployeeBank" type="checkbox" checked={participates} disabled={readOnly} onChange={e=>setParticipates(e.target.checked)}/> Получает одну из четырёх долей дохода</label><div className="sub">Аккаунтов может быть сколько угодно; участников распределения — четыре. Изменение состава не переносит старые доли между людьми.</div><div className="checkboxes">{PERMISSIONS.filter(k=>k!=='users.manage').map(k=><label className="check" key={k}><input name={k} type="checkbox" checked={keys.includes(k)} disabled={readOnly&&!k.endsWith('.view')&&!k.endsWith('.view_all')} onChange={e=>{setKeys(e.target.checked?[...keys,k]:keys.filter(x=>x!==k));setPreset('CUSTOM');}}/>{PERMISSION_LABELS[k]}</label>)}</div><div><button className="btn primary" disabled={pending}>{pending?'Сохранение…':user?'Сохранить права':'Создать пользователя'}</button></div>{state.error&&<div className="notice" role="alert">{state.error}</div>}{state.success&&<div className="success" role="status">{state.success}</div>}</form>;
}
